<?php 

return [
    [
        'first_name' => 'Marco',
        'last_name' => 'Canopoli',
        'email' => 'canopoli.marco@gmail.com',
        'password' => 'pippo',
        'birthdate' => '1991-08-25',
        'phone' => '+393454589565',
        'about' => 'Eccoci, rientriamo',
        'profile_pic' => 'users/1/profile_pics/A8HnrL7Vd1Jh8pBZ6uRF4uBeqbOKeiqHvieSMDQX.jpg',
    ],
    [
        'first_name' => 'Luca',
        'last_name' => 'Sbarbaro',
        'email' => 'sbarbaro.luca@gmail.com',
        'password' => 'pippo',
        'birthdate' => '1991-08-25',
        'phone' => '+393424751368',
        'about' => 'Eccoci, rientriamo',
        'profile_pic' => 'users/2/profile_pics/NfUlLIIAwhMWOa86bZ0qYG3fbI5hlkbNGd4txy80.jpg',
    ],
    [
        'first_name' => 'Patrizio',
        'last_name' => 'Sbrozzi',
        'email' => 'sbrozzi.patrizio@gmail.com',
        'password' => 'pippo',
        'birthdate' => '1991-08-25',
        'phone' => '+393496458123',
        'about' => 'Eccoci, rientriamo',
        'profile_pic' => 'users/3/profile_pics/MwVXmWbTWqMTPW1c9XmFnYjw35mTjaFKdBsxLIay.jpg',
    ],
    [
        'first_name' => 'Luca',
        'last_name' => 'Quacquarelli',
        'email' => 'quacquarelli.luca@gmail.com',
        'password' => 'pippo',
        'birthdate' => '1991-08-25',
        'phone' => '+393487613457',
        'about' => 'Eccoci, rientriamo',
        'profile_pic' => 'users/4/profile_pics/xeSkjco2mV49ecTvoyN6Q0tjPalUuJtSeGTY8VAM.jpg',
    ],
    [
        'first_name' => 'Alessandro',
        'last_name' => 'De Santis',
        'email' => 'desantis_alessandro@gmail.com',
        'password' => 'pippo',
        'birthdate' => '1991-08-25',
        'phone' => '+393448612347',
        'about' => 'Eccoci, rientriamo',
        'profile_pic' => 'default-user.png',
    ],
];  
